### ISSUE TITLE
ESP8266 Mesh Network

### ISSUE THREAD

**Issue by crosofg** [souliss/souliss#207]
Hi Can any sort of mesh networking be achieved using Souliss Framework?
Can you guys give something to start?

**Comment by plinioseniore** [comment]
The ESP8266 cores for Arduino has example for WiFi mesh, I'm having a look
at to understand how it works and if can be used with Souliss

**Comment by plinioseniore** [comment]
@crosofg had a quick look, the ESP8266 cores for Arduino support a very raw mesh that is basically a mix of STA and AP mode, so that nodes can interconnect but it doesn't offer any routing, so isn't a mesh at all.

Souliss doesn't have a mesh, but a tree structure and you can use it with a combination of STA (connection to an access point) and AP (access point), if you are interested to cover a longer range we can have a try.

**Comment by crosofg** [comment]
Yeah longer range will be great. Can you have a look at this? 
https://github.com/espressif/ESP8266_LIGHT_WITH_MESH

**Comment by crosofg** [comment]
Hi Did you get a chance to look the mesh implementation provided by Espressif?

**Comment by plinioseniore** [comment]
You can try your self combining STA and AP mode to get your needs.

**Comment by kubark42** [comment]
This does seem to be the killer application for this stuff. I'd like to have a home automation work on a MDU (multiple dwelling unit) and so mesh is critical to making it work since we don't have an in-building network.
