### ISSUE TITLE
T16 and T19 music sync line in

### ISSUE THREAD

**Issue by dariocdj** [souliss/souliss#307]
It can be marvellous to have as music source "line in", because mic isn't reliable

**Comment by shineangelic** [comment]
AFAIK this is impossible, since Android API doesn't provide a line-in media record nor the average phone has a stereo line in...Some sort of plug-in/dongle is needed. For a better explanation see https://stackoverflow.com/questions/12192295/android-get-audio-signal-from-the-audio-line-in-instead-of-phone-microphone
